# Generated by Django 3.0.8 on 2020-08-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_auto_20200825_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visits',
            new_name='Visit',
        ),
    ]
