# Generated by Django 3.0.8 on 2020-08-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0003_auto_20200825_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='page_visits',
            new_name='page_visitss',
        ),
    ]
