# Generated by Django 3.0.8 on 2020-08-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_auto_20200825_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='page_visitss',
        ),
    ]
