# Generated by Django 3.0.8 on 2020-08-26 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0005_remove_visit_page_visitss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='date_of_visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='page_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='Time_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 8, 20, 34, 766823, tzinfo=utc), verbose_name='Time Visited'),
        ),
    ]
