# Generated by Django 3.0.8 on 2020-08-26 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0006_auto_20200826_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Time_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 12, 27, 56, 799415, tzinfo=utc), verbose_name='Time Visited'),
        ),
    ]
