# Generated by Django 3.0.8 on 2020-08-27 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0009_auto_20200826_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='The IP address that should be banned', verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Banned IP',
                'verbose_name_plural': 'Banned IPs',
                'ordering': ('ip_address',),
            },
        ),
        migrations.CreateModel(
            name='UntrackedUserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='Part or all of a user-agent string.  For example, "Googlebot" here will be found in "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" and that visitor will not be tracked.', max_length=100, verbose_name='keyword')),
            ],
            options={
                'verbose_name': 'Untracked User-Agent',
                'verbose_name_plural': 'Untracked User-Agents',
                'ordering': ('keyword',),
            },
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='Time_of_visit',
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='page_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 8, 21, 27, 647457, tzinfo=utc), null=True),
        ),
    ]
