# Generated by Django 3.0.8 on 2020-08-27 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0010_auto_20200827_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('act', 'Active'), ('inact', 'Inactive')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 10, 16, 5, 799201, tzinfo=utc), null=True),
        ),
    ]
