# Generated by Django 3.0.8 on 2020-08-27 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0011_auto_20200827_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 10, 21, 43, 350237, tzinfo=utc), null=True),
        ),
    ]
